# set alpine as backend OS
FROM alpine:3.14

ARG JDK_VER=openjdk17

# Install dependencies
RUN apk update \
    && apk add --no-cache ca-certificates ${JDK_VER} python3 py3-dev py3-venv py3-pip zip hmmer perl wget \
    && rm -rf /var/cache/apk/*

COPY . /app/pprcode

# Install pip packages
RUN pip3 install --upgrade pip \
    && pip3 install pandas biopython matplotlib dna_features_viewer xlsxwriter absl-py==0.13.0

# PS_scan setting/ PPRfinder setting
ARG PROSITE_URL='https://ftp.expasy.org/databases/prosite/'
ARG PS_SCAN_URL='https://ftp.expasy.org/databases/prosite/ps_scan/ps_scan_linux_x86_elf.tar.gz'
ARG PPRFINDER_BUILD='https://raw.githubusercontent.com/YaoYinYing/PPRfinder/master/out/production/PPRfinder/PPRfinder.jar'
ARG HMM_PROFILE_URL='https://raw.githubusercontent.com/YaoYinYing/PPRfinder/master/data/'

# setup psscan
RUN wget -qnc ${PS_SCAN_URL} -P /tmp \
    && mkdir -p /app/bin/ \
    && cd /app/bin/ \
    && tar zxf /tmp/ps_scan_linux_x86_elf.tar.gz \
    && rm /tmp/ps_scan_linux_x86_elf.tar.gz

RUN  wget -qnc ${PPRFINDER_BUILD} -P /app/bin/

RUN mkdir /app/profiles \
    && wget -qnc ${PROSITE_URL}/prosite.dat -P /app/profiles/ \
    && wget -qnc ${HMM_PROFILE_URL}/all_PPR.hmm -P /app/profiles/

# Add SETUID bit to the ldconfig binary so that non-root users can run it.
RUN chmod u+s /sbin/ldconfig

WORKDIR /app/pprcode

ENV PATH="/app/bin/ps_scan:$PATH"

RUN echo $'#!/bin/sh\n\
ldconfig\n\
python3 /app/pprcode/docker/run_pprcode.py "$@"' > /app/run_pprcode.sh \
  && chmod +x /app/run_pprcode.sh
ENTRYPOINT ["/app/run_pprcode.sh"]
