name: PPRCODE_Guideline Workflow

on:
  push:
    paths:
      - 'docker/**' # Monitor the entire 'docker' directory
      - 'scripts/**' # Monitor the entire 'scripts' directory
      - 'README.md'  # Monitor the 'README.md' file
      - '.github/**'
    branches:
      - master
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set environment variable with current date
      run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
    - name: Build Docker image
      run: docker build -f docker/Dockerfile -t pprcode .

    - name: Tag Docker image with date and latest
      run: |
        docker tag pprcode yaoyinying/pprcode:${{ env.DATE }}
        docker tag pprcode yaoyinying/pprcode:latest

    - name: Log in to Docker Hub
      run: docker login -u YaoYinYing -p ${{ secrets.DOCKER_GITHUB_REPO_SECRET }}

    - name: Push Docker image
      run: |
        docker push yaoyinying/pprcode:${{ env.DATE }}
        docker push yaoyinying/pprcode:latest
        
    - name: Update Docker Hub README.md
      run: |
        docker cp README.md yaoyinying/pprcode:/README.md
        docker commit yaoyinying/pprcode yaoyinying/pprcode
        docker push yaoyinying/pprcode

        
#     - name: Install pybiolib package
#       run: pip3 install -U pybiolib
      
#     - name: Build and push biolib application
#       run: BIOLIB_TOKEN=${{ secrets.BIOLIB_TOKEN }} biolib push https://biolib.com/YaoYinYing/pprcode/
