name: PPRCODE_Guideline Workflow

on:
  push:
    paths:
      - 'docker/**' # Monitor the entire 'docker' directory
      - 'scripts/**' # Monitor the entire 'scripts' directory
      - 'README.md'  # Monitor the 'README.md' file
      - '.github/**'
    branches:
      - master
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set environment variable with current date
      run: |
        echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "DATE: ${{ env.DATE }}"
    
    - name: Set environment variable with current repo dir
      run: |
        echo "REPO=$PWD" >> $GITHUB_ENV
        echo "REPO: ${{ env.REPO }}"
      
    - name: Build Docker image
      run: docker build -f docker/Dockerfile -t pprcode .

    - name: Tag Docker image with date and latest
      run: |
        docker tag pprcode yaoyinying/pprcode:${{ env.DATE }}
        docker tag pprcode yaoyinying/pprcode:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_GITHUB_REPO_SECRET }}" | docker login -u yaoyinying --password-stdin

    # - name: Create Testing and Run it
    #   run: |
    #     python -m venv pprcode_test
    #     source pprcode_test/bin/activate
    #     pip install -r docker/requirements.txt
    #     python ${{ env.REPO }}/docker/run_docker.py --fasta ${{ env.REPO }}/PPR_example.fasta --save_dir ./save-psscan --plot_item=bar,score,edge,ppr,rna
    #     python ${{ env.REPO }}/docker/run_docker.py --fasta ${{ env.REPO }}/PPR_example.fasta --save_dir ./save-pprfinder --plot_item=bar,score,edge,ppr,rna --program=pprfinder
    #     deactivate 
        
    - name: Push Docker image
      run: |
        cd ${{ env.REPO }}
        docker push yaoyinying/pprcode:${{ env.DATE }}
        docker push yaoyinying/pprcode:latest
        
    - name: Update Docker Hub README.md
      run: |
        cd ${{ env.REPO }}
        docker cp README.md yaoyinying/pprcode:/README.md
        docker commit yaoyinying/pprcode yaoyinying/pprcode
        docker push yaoyinying/pprcode
        
    - name: Install pybiolib package
      run: pip3 install -U pybiolib

    - name: Update Readme file to Biolib
      run: sed -e 's|\.\/image\/|https:\/\/raw.githubusercontent.com\/YaoYinYing\/PPRCODE_Guideline\/master\/image\/|g; s|(\image|(https:\/\/raw.githubusercontent.com\/YaoYinYing\/PPRCODE_Guideline\/master\/image|g' README.md >README.biolib.md
      
    - name: Build and push biolib application
      run: BIOLIB_TOKEN=${{ secrets.BIOLIB_TOKEN }} biolib push https://biolib.com/YaoYinYing/pprcode/

    - name: Delete BioLib Readme
      run: rm -f README.biolib.md